### ISSUE TITLE
include upstream info

### ISSUE THREAD

**Issue by ptrebert** [core-unit-bioinformatics/template-metadata-files#8]
I propose the following section to be added to the `pyproject.toml` for a workflow that is based on a fork:

```toml
[cubi.workflow]
pid = "undefined"
name = "undefined"
version = "prototype"

[cubi.workflow.upstream]
pid = "undefined"  # could be DOI, or just URL if no persistent identifier exists
name = "undefined"  # the name ...
version = "prototype"  # the forked version, updated with each release that is pulled
```

What do you think?
